# Generated by Django 5.2.8 on 2025-11-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "run",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                ("dv", models.CharField(blank=True, max_length=1, null=True)),
                ("inmigrante", models.BooleanField(default=False)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pueblo_originario", models.BooleanField(default=False)),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("discapacidad", models.BooleanField(default=False)),
                ("privada_libertad", models.BooleanField(default=False)),
                ("trans_masculino", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "Paciente",
            },
        ),
        migrations.CreateModel(
            name="Hospitalizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ingreso", models.DateField(blank=True, null=True)),
                ("fecha_alta", models.DateField(blank=True, null=True)),
                ("motivo", models.CharField(blank=True, max_length=200, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizaciones",
                        to="pacientesApp.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalización",
                "verbose_name_plural": "Hospitalizaciones",
                "db_table": "Hospitalizacion",
            },
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(fields=["run"], name="idx_paciente_run"),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["apellido_paterno"], name="idx_paciente_apellido"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalizacion",
            index=models.Index(
                fields=["paciente", "fecha_ingreso"], name="idx_hosp_paciente_fecha"
            ),
        ),
    ]
