# Generated by Django 5.2.8 on 2025-12-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientesApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalizacion",
            name="fecha_alta",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="hospitalizacion",
            name="fecha_ingreso",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="dv",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="edad",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nacionalidad",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="run",
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
