# Generated by Django 5.2.8 on 2025-12-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientesApp", "0002_alter_hospitalizacion_fecha_alta_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_paciente",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSTIT", "Institucional"),
                            ("PREH", "Prehospitalario"),
                            ("FUERA_RED", "Fuera de la Red Asistencial"),
                            ("DOM_PROF", "Domicilio con Atención Profesional"),
                            ("DOM_NOPROF", "Domicilio sin Atención Profesional"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "origen_ingreso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("URG", "Urgencia"),
                            ("SALA", "Sala"),
                            ("SAMU", "Derivación SAMU"),
                            ("CPREN", "Control Prenatal"),
                            ("HOSP", "Hospitalización previa"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tipo_parto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("V_EUT", "Parto vaginal eutócico"),
                            ("V_INS", "Parto vaginal instrumental"),
                            ("CES_ELE", "Cesárea electiva"),
                            ("CES_URG", "Cesárea urgencia"),
                            ("POD", "Presentación podálica"),
                            ("GEM", "Parto gemelar"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "clasificacion_robson",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G1", "Grupo 1"),
                            ("G2A", "Grupo 2.A"),
                            ("G2B", "Grupo 2.B"),
                            ("G3", "Grupo 3"),
                            ("G4", "Grupo 4"),
                            ("G51", "Grupo 5.1"),
                            ("G52", "Grupo 5.2"),
                            ("G6", "Grupo 6"),
                            ("G7", "Grupo 7"),
                            ("G8", "Grupo 8"),
                            ("G9", "Grupo 9"),
                            ("G10", "Grupo 10"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "posicion_materna",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SEMIS", "Semisentada"),
                            ("SENT", "Sentada"),
                            ("LIT", "Litotomía"),
                            ("DDOR", "Decúbito Dorsal"),
                            ("CUAD", "Cuadrúpeda"),
                            ("DLAT", "Decúbito Lateral"),
                            ("DEPIE", "De Pie"),
                            ("CUCL", "Cuclillas"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "estado_perine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INDEM", "Indemne"),
                            ("EPIS", "Episiotomía"),
                            ("G1", "Desgarro Grado 1"),
                            ("G2", "Desgarro Grado 2"),
                            ("G3A", "Desgarro Grado 3A"),
                            ("G3B", "Desgarro Grado 3B"),
                            ("G3C", "Desgarro Grado 3C"),
                            ("G4", "Desgarro Grado 4"),
                            ("FIS", "Fisura"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tipo_regimen",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IOP", "IOP"),
                            ("RAM", "RAM"),
                            ("REM_COM", "REM Común"),
                            ("RPM", "RPM"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("fecha", models.DateField(blank=True, null=True)),
                ("hora", models.TimeField(blank=True, null=True)),
                ("plan_parto", models.BooleanField(default=False)),
                ("visita_guiada", models.BooleanField(default=False)),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("paridad", models.IntegerField(blank=True, null=True)),
                ("control_prenatal", models.BooleanField(default=False)),
                (
                    "consultorio_origen",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("nro_aro", models.IntegerField(blank=True, null=True)),
                ("sem_obst_semanas", models.IntegerField(blank=True, null=True)),
                ("sem_obst_dias", models.IntegerField(blank=True, null=True)),
                ("monitor", models.BooleanField(default=False)),
                ("ttc", models.BooleanField(default=False)),
                ("induccion", models.BooleanField(default=False)),
                ("aceleracion", models.BooleanField(default=False)),
                ("nro_tv", models.IntegerField(blank=True, null=True)),
                ("rotura_membrana", models.BooleanField(default=False)),
                (
                    "tiempo_membranas_rotas",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tiempo_dilatacion",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tiempo_expulsivo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("libertad_movimiento", models.BooleanField(default=False)),
                ("alumbramiento_dirigido", models.BooleanField(default=False)),
                ("ofrecimiento_posiciones", models.BooleanField(default=False)),
                ("esterilizacion", models.BooleanField(default=False)),
                ("revision", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("uso_sala_saip", models.BooleanField(default=False)),
                ("folio_valido", models.BooleanField(default=False)),
                ("folio_nulo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partos",
                        to="pacientesApp.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parto",
                "verbose_name_plural": "Partos",
                "db_table": "Parto",
            },
        ),
        migrations.CreateModel(
            name="OtrosDatos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ley_dominga", models.BooleanField(default=False)),
                ("placenta", models.BooleanField(default=False)),
                ("registro_civil", models.BooleanField(default=False)),
                ("recuerdos_entregados", models.BooleanField(default=False)),
                ("motivo_no_recuerdos", models.TextField(blank=True, null=True)),
                ("retira_placenta", models.BooleanField(default=False)),
                ("estampado_placenta", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otrosdatos",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otros Datos",
                "verbose_name_plural": "Otros Datos",
                "db_table": "OtrosDatos",
            },
        ),
        migrations.CreateModel(
            name="Examenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vih_preparto", models.BooleanField(default=False)),
                ("vih_sala", models.BooleanField(default=False)),
                ("pesquisa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "resultado_vih",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REACT", "Reactivo"),
                            ("NO_REACT", "No Reactivo"),
                            ("POS", "Positivo"),
                            ("NEG", "Negativo"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("antibiotico_sgb", models.BooleanField(default=False)),
                (
                    "resultado_vdrl",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REACT", "Reactivo"),
                            ("NO_REACT", "No Reactivo"),
                            ("POS", "Positivo"),
                            ("NEG", "Negativo"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("tratamiento_sifilis", models.BooleanField(default=False)),
                ("examen_hepatitis_b", models.BooleanField(default=False)),
                ("derivacion_hepatologo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examenes",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Exámenes",
                "db_table": "Examenes",
            },
        ),
        migrations.CreateModel(
            name="Apego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tiempo_apego",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("apego_canguro", models.BooleanField(default=False)),
                ("acomp_preparto", models.BooleanField(default=False)),
                ("acomp_parto", models.BooleanField(default=False)),
                ("acomp_rn", models.BooleanField(default=False)),
                ("motivo_no_acompanamiento", models.TextField(blank=True, null=True)),
                (
                    "persona_acompanante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAREJA", "Pareja"),
                            ("MADRE", "Madre"),
                            ("PADRE", "Padre"),
                            ("AMIGA", "Amiga"),
                            ("HERMANA", "Hermana"),
                            ("DOULA", "Doula"),
                            ("NINGUNA", "Ninguna"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("corta_cordon", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apego",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apego",
                "verbose_name_plural": "Apegos",
                "db_table": "Apego",
            },
        ),
        migrations.CreateModel(
            name="Anestesia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("neuroaxial", models.BooleanField(default=False)),
                ("oxido_nitroso", models.BooleanField(default=False)),
                ("analgesia_endovenosa", models.BooleanField(default=False)),
                ("general", models.BooleanField(default=False)),
                ("local", models.BooleanField(default=False)),
                ("no_farmacologica", models.BooleanField(default=False)),
                ("balon_kinesico", models.BooleanField(default=False)),
                ("lenteja_parto", models.BooleanField(default=False)),
                ("rebozo", models.BooleanField(default=False)),
                ("aromaterapia", models.BooleanField(default=False)),
                ("peridural_solicitada", models.BooleanField(default=False)),
                ("peridural_indicada", models.BooleanField(default=False)),
                ("peridural_administrada", models.BooleanField(default=False)),
                (
                    "tiempo_espera_peridural",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anestesia",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anestesia",
                "verbose_name_plural": "Anestesias",
                "db_table": "Anestesia",
            },
        ),
        migrations.CreateModel(
            name="Patologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preeclampsia_severa", models.BooleanField(default=False)),
                ("eclampsia", models.BooleanField(default=False)),
                ("sepsis_grave", models.BooleanField(default=False)),
                ("infeccion_ovular", models.BooleanField(default=False)),
                ("otra_patologia", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patologias",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patología",
                "verbose_name_plural": "Patologías",
                "db_table": "Patologia",
            },
        ),
        migrations.CreateModel(
            name="Procedimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inercia_uterina", models.BooleanField(default=False)),
                ("restos_placentarios", models.BooleanField(default=False)),
                ("trauma", models.BooleanField(default=False)),
                ("alteracion_coagulacion", models.BooleanField(default=False)),
                ("manejo_quirurgico", models.BooleanField(default=False)),
                ("histerectomia", models.BooleanField(default=False)),
                ("transfusion", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimiento",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimiento",
                "verbose_name_plural": "Procedimientos",
                "db_table": "Procedimiento",
            },
        ),
        migrations.CreateModel(
            name="Profesionales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("alumno", models.CharField(blank=True, max_length=200, null=True)),
                ("causa_cesarea", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profesionales",
                        to="partosApp.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesional",
                "verbose_name_plural": "Profesionales",
                "db_table": "Profesionales",
            },
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(fields=["paciente"], name="idx_parto_paciente"),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(fields=["fecha"], name="idx_parto_fecha"),
        ),
    ]
