# Generated by Django 5.2.8 on 2025-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsuarioApp", "0002_alter_position_permission_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="permission_code",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("SUPERVISOR", "Supervisor"),
                    ("MANAGER", "Matrona"),
                    ("RESTRICTED", "Usuario"),
                ],
                default="RESTRICTED",
                max_length=25,
            ),
        ),
    ]
